---
ID: "58d14237-3391-41fd-8a9c-ef67af49e58e"
Parent: "178e3cec-ca03-4c76-9ad3-122297e19e13"
Template: "178e3cec-ca03-4c76-9ad3-122297e19e13"
Path: /sitecore/templates/Feature/AFL Page Templates/PDP_AdditionalImage/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/16x16/photo_scenery.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220118T161220Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\archana
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\archana
    - ID: "80203708-a0db-4f4b-bd18-b5f74b33756d"
      Hint: ImageTitle
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "790b2a2e-57d2-4902-a652-bf6f802def51"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\archana
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220118T161316Z
