---
ID: "d0ab1f0b-5582-422f-9f49-d60d0fe30aea"
Parent: "9fa90769-b07f-4dd5-9b46-abb4875fff2d"
Template: "9fa90769-b07f-4dd5-9b46-abb4875fff2d"
Path: /sitecore/templates/Feature/AFL Page Templates/High Level Result Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211209T062215Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\archana
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\archana
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cd5802ab-acb2-49ac-8fe3-82396e15fa3e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\archana
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211209T062215Z
