---
ID: "4e682fcf-550a-4494-98a8-99c82870e970"
Parent: "0deeadfe-deaf-4025-9874-639242dfae68"
Template: "c14b6289-8ac2-439c-9e5b-40de9f820c3f"
Path: "/sitecore/content/AFL-Global/OCEANIA/Home/Company/Environment Health Safety/Environmental Sustainability"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{A2709B15-36DB-4B3E-86F8-6278F864C079}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231004T170648Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7d4272f3-b5cd-4e80-a310-69f5a1be73ee"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rafael
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231004T170846Z
