---
ID: "6bffc019-747a-4354-bee5-f032c1d82f8f"
Parent: "d0ed7800-710a-421f-a6e6-90e03bdd570a"
Template: "bf61de11-b78f-48ea-aaa4-1d17f0d83824"
Path: "/sitecore/content/AFL-Global/EMEA/Home/Resources/Product Related Materials"
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{0C0438D1-FDB2-4CD1-8469-63890F800C2D}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: PRODUKTBEZOGENE MATERIALIEN
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: PRODUKTBEZOGENE MATERIALIEN
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{6BFFC019-747A-4354-BEE5-F032C1D82F8F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: PRODUKTBEZOGENE MATERIALIEN
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e79430c-a5ee-48a5-98af-7aa03097a9a1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T095750Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Related Materials
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tanishka
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Product Related Materials
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{6BFFC019-747A-4354-BEE5-F032C1D82F8F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: Product Related Materials
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "050298e0-1ab1-403f-8cfc-c9b0438fc156"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T095750Z
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Related Materials
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Product Related Materials
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{6BFFC019-747A-4354-BEE5-F032C1D82F8F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0427f932-1d4f-440f-b052-baae6955e8c2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mahesh
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220224T113735Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: MATERIALES RELACIONADOS CON EL PRODUCTO
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: MATERIALES RELACIONADOS CON EL PRODUCTO
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{6BFFC019-747A-4354-BEE5-F032C1D82F8F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: MATERIALES RELACIONADOS CON EL PRODUCTO
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0e430b1b-dd5f-4819-b232-9110cb49c77b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T095750Z
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: MATÉRIAUX LIÉS AU PRODUIT
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: MATÉRIAUX LIÉS AU PRODUIT
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{6BFFC019-747A-4354-BEE5-F032C1D82F8F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: MATÉRIAUX LIÉS AU PRODUIT
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "109f0215-9b2e-484c-be32-c15258835491"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T095750Z
