---
ID: "45a7ff27-ad77-47fa-b2f1-c991ba1988bb"
Parent: "15457d5e-b9a4-4c6a-b04b-3ddf53a57a44"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: "/sitecore/content/AFL-Global/OCEANIA/Presentation/Cache Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211027T075726Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "47c82a98-5803-4a62-a7d4-0f61cf1a2cdd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211027T075726Z
