---
ID: "d5f3b2c2-ee96-495f-b04b-5c9a21a482ac"
Parent: "7e830460-983b-4f13-9934-63a8aa6e7de4"
Template: "8fcd3cfe-8b3b-423e-8176-6a7c72cb43fc"
Path: "/sitecore/content/AFL-Global/OCEANIA/Presentation/Rendering Variants/AFL-FeatureProduct/AFL-Content/Content Body/Product Title"
SharedFields:
- ID: "8a85a595-3298-4eb1-96dd-c882ee5802ae"
  Hint: Tag
  Value: "{AD7A95FD-05D0-484E-8AFB-FB1DDD5F44AB}"
- ID: "936e68b4-5346-4adb-9b77-79771d0b40dc"
  Hint: Template
  Value: "{{ sc_translate 'PRODUCT DESCRIPTION' }}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220110T140540Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\archana
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\archana
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0c6a9e49-3888-447a-8a38-23f59e79fc34"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mahesh
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220314T105155Z
