---
ID: "eca1d62e-dbe3-4f5d-b233-b349fbe3e625"
Parent: "d5baebaf-d6c3-4117-9200-2d8f8342ac04"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: "/sitecore/media library/Themes/AFL-Global/AFL-Oceania/AFL-Oceania/sass/base"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211029T114452Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "22b022ed-aea2-44b4-a5d7-c7e6f356cb73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211029T114452Z
