---
ID: "19ac17da-4e90-4ef5-b13c-b7af5ebb2702"
Parent: "44701e42-512a-4ce7-b452-a0ac3962eb4f"
Template: "506098a9-f48f-4041-b144-e47bfb31a67a"
Path: /sitecore/content/AFLGlobal/APAC/Home/Products
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Network/16x16/certificate.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {506098A9-F48F-4041-B144-E47BFB31A67A}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {BF61DE11-B78F-48EA-AAA4-1D17F0D83824}
    {9F3EB887-7A2A-4E1D-A23D-E79337D45CC8}
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Value: 
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{00726E95-BCD9-482C-96E6-29CB9712B537}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\AFLProductAuthor|pe|+item:rename|+item:write|+item:read|+item:create|pd|+item:rename|+item:write|+item:read|+item:create|au|sitecore\ChrisZ|pe|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|pd|-item:rename|-item:delete|-item:create|-item:admin|-item:write|+item:read|^*|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{31A0AACB-BBFD-4866-B407-5D5E72CFAE4C}"
              p:before="*"
              s:ds=""
              s:id="{BFBD9DE2-3ABF-4078-BBCB-C95C5B2D863F}"
              s:par="BreadcrumbRoot&amp;Separator=%2F&amp;IsNavigation&amp;Filter=%7BE0A2A027-0932-4878-A7D6-0416D5263EFB%7D&amp;Reset Caching Options&amp;GridParameters&amp;FieldNames&amp;Styles=%7B7CFA8C19-FDA6-42E5-A975-CE82518DE0E9%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
              s:ph="main"
              s:ccb="Clear on publish" />
            <r
              uid="{BED325A9-1976-4D84-BD7A-3F9DF0B7F8CC}"
              p:after="r[@uid='{31A0AACB-BBFD-4866-B407-5D5E72CFAE4C}']"
              s:ds="query:self::"
              s:id="{6162223D-9EAA-490C-A628-DA2A76933DD4}"
              s:par="Reset Caching Options&amp;GridParameters&amp;FieldNames=%7BEAB2B2BB-1097-4FFB-8011-E7B6EA6BCF97%7D&amp;Styles=%7BC1F65B16-3E15-4B04-9739-1C377B719A76%7D%7C%7B27CAFFAB-D94E-4B2F-8A1C-51294F2D0665%7D%7C%7B7CFA8C19-FDA6-42E5-A975-CE82518DE0E9%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
              s:ph="main"
              s:ccb="Clear on publish" />
            <r
              uid="{B925D228-0D21-49D7-BA38-DBACA8F81385}"
              p:after="*[1=2]"
              s:ds="query:self::"
              s:id="{13D7D189-4AE0-405E-BA41-27D9571590FA}"
              s:par="Reset Caching Options&amp;GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;FieldNames=%7BE81617F3-5E31-4467-B546-45F80DE40936%7D&amp;Styles=%7BC1F65B16-3E15-4B04-9739-1C377B719A76%7D%7C%7B27CAFFAB-D94E-4B2F-8A1C-51294F2D0665%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
              s:ph="main"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211201T123930Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\archana
    - ID: "528986cc-6ff9-4383-8bee-514f0e8172cf"
      Hint: MetaDescription
      Value: "Fiber Optic Cable - AFL offers optical ground wire (OPGW), all-dielectric self-supporting (ADSS) cabling, premise/enterprise cable, loose tube and specialty fiber optic cables."
    - ID: "56611f02-691a-4096-b044-63aa83122916"
      Hint: Content
      Value: |
        <h1>Products</h1>
        <h2>
        AFL&rsquo;s products combine to provide unique end-to-end solutions for customer<br />
        &nbsp;</h2>
        <p>
        Customers around the world have relied on AFL&rsquo;s quality and proven products for over three decades. We engineer each product to deliver exactly as promised, and we have a culture of constantly creating new products to better meet the needs of our customers.</p>
        <div>
        <p>
        AFL&rsquo;s products are supported by our Services offerings.</p>
        <p>
        When you choose AFL, you will be working closely with our team of dedicated professionals that are ready to assist you at every step in the process. Their knowledge and expertise will help you build a true end-to-end solution for your particular application.</p>
        </div>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\archana
    - ID: "5e650555-c7f0-456a-8185-f69388169cbc"
      Hint: MetaKeywords
      Value: "fiber optic cable optical ground wire OPGW all-dielectric self-supporting ADSS premise loose tube specialty cables"
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: AFLProducts1
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: AFLProducts1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1414f684-d633-40f4-b5ae-526a30f391cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231129T145202Z
