---
ID: "954ba79d-4d44-4041-9022-f18907c6b365"
Parent: "d33943ec-9785-41e3-8392-1303c5efd0e9"
Template: "bf61de11-b78f-48ea-aaa4-1d17f0d83824"
Path: "/sitecore/content/AFL-Global/OCEANIA/Home/Contact/Product Sales Team"
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Value: |
    {E0A2A027-0932-4878-A7D6-0416D5263EFB}
    {61BD64D6-809E-40AE-9297-2724A19329B3}
    {D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}
    {500AE4C0-FA7B-463F-8149-EFFF7F044101}
    {A0E7FF57-6994-4B09-AA21-104239628D5A}
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{EDC9686A-85F3-466E-8E7E-3D28540B77AB}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{DAE7C21D-4D3B-4257-A95C-9104CD8AF409}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "db51d4e9-c24d-4670-af0e-62c8aa08e2b6"
  Hint: LocalData
  Value: "{A3551059-E8EB-425C-9E63-448546C3A276}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{58BC93D3-2D3E-4E31-8BC9-1F133E079E23}"
              s:ds="local:/Data/HTML Code 1"
              s:id="{6DDA07A9-18D3-47A0-AB74-DF54956DD5F1}"
              s:par="Reset Caching Options&amp;GridParameters={908E2BC6-C110-4ED7-AF39-7EEACBB31A34}&amp;Styles&amp;CacheClearingBehavior=Clear on publish&amp;RenderingIdentifier"
              s:ph="/main/sxa-high-level-page/container-5" />
          </d>
        </r>
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link linktype="external" url="https://www.aflglobal.com/en/Contact/Product-Sales-Team" anchor="" target="_blank" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220311T181728Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{1A24FC12-1F8E-4214-921E-D355AA3E4DC5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Sales Team
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\matt
    - ID: "528986cc-6ff9-4383-8bee-514f0e8172cf"
      Hint: MetaDescription
      Value: Find a customer server rep, sales rep and sales agent for your product or support needs.
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\matt
    - ID: "5e650555-c7f0-456a-8185-f69388169cbc"
      Hint: MetaKeywords
      Value: AFL CSR and Sales reps agents team lookup tool find locate
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Product Sales Team
    - ID: "612fc437-a34e-408c-a80f-a3ce18887805"
      Hint: SuggestionBoxRedirectIcon
      Value: 
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: Product Sales Team
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea12aa53-c801-4620-8129-b05d79b316b6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T093801Z
