---
ID: "3e44bd8c-a040-4756-a14a-118796f21287"
Parent: "eddde774-5bbc-4b8a-89ed-ec2b0f7f6a75"
Template: "eddde774-5bbc-4b8a-89ed-ec2b0f7f6a75"
Path: /sitecore/templates/Feature/AFL/PageContent/AFL NewsRoom/AFL News Room Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {EDDDE774-5BBC-4B8A-89ED-EC2B0F7F6A75}
    {0F0CDCAA-2E48-4178-B38F-2FF7CD9DC35A}
    {CAF76CAA-6EF5-40D7-A95E-2D34AA3E980E}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211112T134638Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ed3cd727-57af-4c52-812a-41e8315679f8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        serialization\UnicornDataProvider
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240229T052235Z
