---
ID: "00531d29-ca58-47d5-ac01-c9fcbf0a022f"
Parent: "ded0ce3f-38cd-41a3-ac8e-4a104058c442"
Template: "bf61de11-b78f-48ea-aaa4-1d17f0d83824"
Path: "/sitecore/content/AFL-Global/OCEANIA/Home/Resources/Product Related Materials"
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{DE1A00CE-F907-4D1E-821C-2F653E944E0F}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{C417C3D3-C0CC-4E96-90FE-A8A199206C7C}"
              p:before="*"
              s:ds=""
              s:id="{BFBD9DE2-3ABF-4078-BBCB-C95C5B2D863F}"
              s:par="BreadcrumbRoot&amp;Separator=%2F&amp;IsNavigation&amp;Filter&amp;Reset Caching Options&amp;GridParameters&amp;FieldNames&amp;Styles=%7B592CA5BE-A535-4EE9-A79A-775A8659B0E5%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
              s:ph="main"
              s:ccb="Clear on publish" />
            <r
              uid="{7BD020B3-0D46-41D5-ACA5-8FC4BA1F461F}"
              p:after="r[@uid='{C417C3D3-C0CC-4E96-90FE-A8A199206C7C}']"
              s:ds=""
              s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
              s:par="Reset Caching Options&amp;GridParameters&amp;BackgroundImage&amp;Styles=%7BBD1A60BF-F56C-4724-AFFF-86B39A9D215B%7D%7C%7B1A3163C3-C552-4BFA-ADC9-C7B3A0DC5BF4%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=4"
              s:ph="main"
              s:ccb="Clear on publish" />
            <r
              uid="{038C8D2B-C2A0-4588-9A73-79005417BA96}"
              p:after="r[@uid='{7BD020B3-0D46-41D5-ACA5-8FC4BA1F461F}']"
              s:ds="{00531D29-CA58-47D5-AC01-C9FCBF0A022F}"
              s:id="{99A633FC-B9A9-44A0-B78A-BCBB08DD02C9}"
              s:par="Reset Caching Options&amp;GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
              s:ph="container-4"
              s:ccb="Clear on publish" />
            <r
              uid="{FCC8C49F-EE93-4654-A4F3-A4F318EA00C2}"
              p:after="*[1=2]"
              s:ds=""
              s:id="{9D3BA81A-EECE-4B5A-9862-0239A9D53EEC}"
              s:par="NavigationRoot=%7B00531D29-CA58-47D5-AC01-C9FCBF0A022F%7D&amp;LevelFrom=%7B1BB88840-5FB3-4353-AD8D-81136F6FF75A%7D&amp;LevelTo=%7B8C72A61D-7BD1-4A4F-98B3-A6869672373B%7D&amp;Filter=%7BA0E7FF57-6994-4B09-AA21-104239628D5A%7D&amp;Flattened&amp;AddRoot&amp;NavigationFieldNames&amp;Reset Caching Options&amp;GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
              s:ph="container-4"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211231T100354Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Related Materials
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tanishka
    - ID: "528986cc-6ff9-4383-8bee-514f0e8172cf"
      Hint: MetaDescription
      Value: Product related resources and materials Australia New Zealand
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tanishka
    - ID: "5e650555-c7f0-456a-8185-f69388169cbc"
      Hint: MetaKeywords
      Value: Product related resources and materials Australia New Zealand
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Product Related Materials
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{00531D29-CA58-47D5-AC01-C9FCBF0A022F}" querystring="" target="|Custom" text="LEARN MORE" anchor="" title="" class="" url="/AFL-Global/OCEANIA/Home/Resources/Product Related Materials" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: Product Related Materials
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e8be322d-3e24-4cbd-8276-a4e95d3fbf17"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sharma.varun@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240229T111727Z
