---
ID: "ab4199ec-5ab5-4473-85ba-9d5576820e47"
Parent: "1c1ee144-dc0c-4973-9f10-0a03d243bf10"
Template: "c14b6289-8ac2-439c-9e5b-40de9f820c3f"
Path: "/sitecore/content/AFL-Global/EMEA/Home/Company/Environment Health Safety/Environmental Sustainability"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link id="{53B2D8F8-3FE2-4601-9AC2-3D55B6955035}" querystring="" target="" text="" anchor="" title="" class="" url="/AFL-Global/EMEA/Home/Company/Corporate Responsibility/Environmental Sustainability" linktype="internal" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231004T174104Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3bec2a5b-18b2-4a76-866c-e4045b452268"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rafael
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231004T175536Z
