---
ID: "dff41177-9f17-425d-a28e-a97b3b92f416"
Parent: "60ce6ec2-905a-472d-843c-a4a904183d11"
Template: "60ce6ec2-905a-472d-843c-a4a904183d11"
Path: /sitecore/templates/Feature/AFL/Custom Carousel Slide/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{B8AB7438-FF88-41A2-B0FD-493FB644E1B2}">
        <r
          ds=""
          id="{8B0393E9-EE25-4F0B-A5FD-777B3AD2C737}"
          par="Reset Caching Options&amp;GridParameters&amp;FieldNames=%7B62BCC5F1-842C-4B0C-A6C9-5D05707EFE9D%7D&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId"
          ph="section-content"
          uid="{CB7B1C66-77F9-45E4-9AA3-12AC3E1EDF5A}"
          ccb="Clear on publish" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CB7B1C66-77F9-45E4-9AA3-12AC3E1EDF5A}"
              s:par="Reset Caching Options&amp;GridParameters&amp;FieldNames=%7B62BCC5F1-842C-4B0C-A6C9-5D05707EFE9D%7D&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T104300Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "78a76547-5058-4165-964a-65df33518412"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        serialization\UnicornDataProvider
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240229T052233Z
