---
ID: "d6a3a11a-deb9-4f84-af9b-e6d12b7188ed"
Parent: "aca39757-0f56-4b9c-b611-06f0d14796ad"
Template: "c14b6289-8ac2-439c-9e5b-40de9f820c3f"
Path: /sitecore/content/AFLGlobal/APAC/Home/Company/Environment Health Safety/Environmental Sustainability
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{D7C0086B-FD36-430A-807E-023D55F307AE}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231004T182847Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2ac9010e-7fcd-4c16-835b-3d22fb8fada9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pawan.tyagi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240316T041638Z
