---
ID: "a2bf1967-c599-4604-9679-2bc9e92818de"
Parent: "aca39757-0f56-4b9c-b611-06f0d14796ad"
Template: "bf61de11-b78f-48ea-aaa4-1d17f0d83824"
Path: /sitecore/content/AFLGlobal/APAC/Home/Company/Environment Health Safety/Environment Sustainability
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{87CE798E-CDA3-4363-A47F-74DF3E2D88BE}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{DAE7C21D-4D3B-4257-A95C-9104CD8AF409}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Environment/Sustainability
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211122T094006Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Environmental Sustainability
    - ID: "528986cc-6ff9-4383-8bee-514f0e8172cf"
      Hint: MetaDescription
      Value: At AFL we are focused on Environmental Sustainability and Stewardship to meet business objectives.
    - ID: "52b07316-e493-41de-8a4f-d5010dc3eebd"
      Hint: Description
      Value: |
        <div class="container-fluid ">
        <div class="offset-md-1 col-md-10 offset-md-1">
        <h2 style="margin-top: -35px;">Since our founding,&nbsp;AFL has focused on environmental stewardship while achieving our business goals.</h2>
        <p>We began with a solid foundation of compliance and have expanded our efforts to not only manage environmental impacts, but also to reduce or eliminate them wherever possible. Because of our focus on environmental stewardship, AFL has become a more efficient and innovative operation, driving costs out of the business and growing into an even stronger company.</p>
        <h2>AFL is committed to operating in a safe and responsible manner worldwide that respects communities and the environment.
        </h2>
        <ul style="padding-left: 0px !important;">
            <li id="body_links">
            <p id="body_links">Globally, our ISO 14001:2015 environmental management system process provides the framework for improvement. AFL shares a lasting commitment to building a better company for future generations in the communities where we live and work. Click for more information on our <a style="font-size: 15px !important;" href="~/link.aspx?_id=85FA31300C93477785F2B78E68099C63&amp;_z=z">ISO 14001:2015&nbsp;certifications</a>.
            </p>
            </li>
            <li id="body_links">
            <p id="body_links">AFL is proud to partner with <a style="font-size: 15px !important;" href="~/link.aspx?_id=320A70EA73C24DDFAA1B30044006E3BC&amp;_z=z">Sonoco&rsquo;s EcoReel&reg; Recycling Program</a>, the most comprehensive and cost-effective nailed wood reel recycling program in the industry, to provide a free removal service for AFL customers.
            </p>
            </li>
            <li id="body_links">
            <p>We are focusing targets and actions in five key areas to further AFL&rsquo;s commitment to environmental sustainability :</p>
            </li>
        </ul>
        <p>
        </p>
        <br />
        <div class="row">
        <div class="col-lg right">
        <img style="text-align: center;" src="https://afl-delivery.stylelabs.cloud/api/public/content/globe?v=48f62807" class="img-responsive center-block d-block mx-auto" alt="..." />
        <div class="col-body">
        <h5 style="color: #C1D82F;" class="col-title ">Reducing Greenhouse Gas (GHG) Emissions</h5>
        <p id="body_links" class="col-text ">
        AFL is committed to do our part to limit global warming and has set ambitious targets in our operations and value chain for climate action in line with the <a rel="noopener noreferrer" href="https://sciencebasedtargets.org/" target="_blank">Science Based Target initiative</a>.
        </p>
        </div>
        </div>
        <div class="col-lg right">
        <img src="https://afl-delivery.stylelabs.cloud/api/public/content/Bolt?v=9d3f7bbb" class="img-responsive center-block d-block mx-auto" alt="..." />
        <div class="col-body">
        <h5 style="color: #C1D82F;" class="col-title ">Operational
        Energy Efficiency</h5>
        <p class="col-text ">
        We aim to reduce our own operational carbon footprint by optimizing our operational energy usage, adopting cleaner fuels and investing in renewable power.
        </p>
        </div>
        </div>
        <div class="col-lg right">
        <img src="https://afl-delivery.stylelabs.cloud/api/public/content/Arrows?v=15d1df51" class="img-responsive center-block d-block mx-auto" alt="..." />
        <div class="col-body">
        <h5 style="color: #C1D82F;" class="col-title ">Circular Economy and Raw Material Efficiency
        </h5>
        <p class="col-text ">
        At AFL, we strive to offer solutions that minimize our customer&rsquo;s environmental impact as well. We are designing our products and packaging with lifecycle sustainability in mind.
        </p>
        </div>
        </div>
        <div class="col-lg right">
        <img src="https://afl-delivery.stylelabs.cloud/api/public/content/Triangle?v=caf3b436" class="img-responsive center-block d-block mx-auto" alt="..." />
        <div class="col-body">
        <h5 style="color: #C1D82F;" class="col-title ">Waste
        Management
        </h5>
        <p class="col-text ">
        AFL is dedicated to conserving natural resources through waste management. We have set goals to minimize scrap rates, optimize reuse and recycling, and ensure appropriate treatment of waste streams.
        </p>
        </div>
        </div>
        <div class="col-lg">
        <img src="https://afl-delivery.stylelabs.cloud/api/public/content/Faucet?v=8930f748" class="img-responsive center-block d-block mx-auto" alt="..." />
        <span id="scrollspyEnvironment"></span>
        <div class="col-body">
        <h5 style="color: #C1D82F;" class="col-title ">Water
        Conservation
        </h5>
        <p class="col-text ">
        Conservation of our planet's most valuable natural resource, water, is vital to sustaining human health and the environment. That's why AFL is prioritizing goals to effectively manage our water consumption.
        </p>
        <span id="scrollspySocial"></span>
        </div>
        </div>
        </div>
        <p id="body_links">For more information, please visit our <a href="~/link.aspx?_id=0D53B7698E2B48ADAC5B770B35370B68&amp;_z=z">Corporate Responsibility Page</a></p>
        <p>&nbsp;</p>
        </div>
        </div>
        <style>
            img {
            max-width: 100%;
            }
            .col, .col-lg {
            height: auto;
            transition: transform 0.2s ease;
            box-shadow: 0 4px 6px 0 rgba(22, 22, 26, 0.18);
            border-radius: 0;
            border: 0;
            margin-bottom: 1.5em;
            }
            .col:hover {
            transform: scale(1.1);
            height: auto;
            }
            .col-lg:hover{
            transform: scale(1.1);
            height: auto;
            }
            .col:hover {
            cursor: pointer;
            }
            .col-lg:hover {
            cursor: pointer;
            }
        </style>
        <style>
            .col-title {
            font-weight: bold !important;
            text-align: center;
            font-size: x-large;
            }
        </style>
        <style>
            .two-cols {
            display: -webkit-box;
            }
            .col {
            word-wrap: normal;
            }
            .col img {
            width: 200px;
            text-align: center;
            }
        </style>
        <style>
            body {
            font-size: 15px;
            font-family: 'Hind',sans-serif !important;
            line-height: 1.4;
            color: #333;
            }
        </style>
        <style>
            . {
            display: none;
            }
            .:hover + . {
            display: block;
            color: #000000;
            }
        </style>
        <style>
            .nav-link {
            text-align: center !important;
            }
            .col ul {
            text-align: left;
            }
            .col img {
            width: 200px !important;
            }
        </style>
        <style>
            .right {
            margin-right: 23px;
            }
            .quote-txt h2 {
            font-size: 3rem;
            color: #FFFFFF !important;
            }
        </style>
        <style>
            .col-text {
            text-align: left;
            }
            .col {
            height: auto !important;
            }
            .col-lg {
            height: auto !important;
            }
            .col-lg ul {
            margin-left: 20%;
            }
            .img-responsive center-block d-block mx-auto {
            text-align: center;
            }
            strong { font-weight: bold; }
            a {
            color: #000000;
            }
        </style>
        <style>
            .container {
            max-width: 100%;
            padding-left: 15px;
            padding-right: 15px;
            }
            #body_links a {
            color: #00c0f3;
            }
            #body_links a:hover {
            color: #004282;
            }
            .container-fluid p, h1, h2, h3, h4, h5, h6 {
            font-family: 'Source Sans Pro', sans-serif !important;
            /*font-weight: 300 !important;*/
            line-height: 1.85em !important;
            font-style: normal !important;
            font-stretch: 100% !important;
            }
            .afl-subPages a {
            word-break: normal;
            }
            /* Extra large devices (large laptops and desktops, 1670px and up) */
            @media only screen and (min-width: 1670px) {
            .offset-md-1 {
            margin-left: 12%;
            }
            .afl-sectioncommonSpace {
            margin-top: 0px !important;
            }
        </style>
    - ID: "56611f02-691a-4096-b044-63aa83122916"
      Hint: Content
      Value: |
        <p>AFL has a long and proven history of focusing on the health and safety of our workforce and the preservation of the environment for the benefit of communities today and future generations. Safety, health and environmental management is a priority area of accountability at AFL. In fact, it is one our<a href="/Company/Company-Profile/AFL-Culture" style="color: #0091ea; background-color: transparent;">Core Values</a>.<br />
        <br />
        Our commitment includes specific short- and long-term goals at our manufacturing sites. Hallmarks of our program include:</p>
        <ul style="color: #333333; background-color: #ffffff; list-style-image: url('https://www.aflglobal.com/productionFiles/images/bulletRound.aspx');">
            <li>
            <p>Providing a safe work environment for all associates</p>
            </li>
            <li>
            <p>Regularly auditing operations at our manufacturing facilities to ensure conformance to our policies</p>
            </li>
            <li>
            <p>Established global safety, health and environmental processes based on regulatory requirements and recognized best practices</p>
            </li>
            <li>
            <p>A record of stewardship that includes careful conservation of the natural resources, including reduction of waste, promotion of recycling and efficiency in our energy and water use</p>
            </li>
            <li>
            <p>Working with customers, suppliers and government agencies to meet our safety, health and environmental responsibilities</p>
            </li>
            <li>
            <p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px;">A culture that focuses on continuous improvement</p>
            </li>
        </ul>
        <p>At AFL, we take the time to ensure that each project is completed in a safe way that reflects our environmental commitment.</p>
    - ID: "5e650555-c7f0-456a-8185-f69388169cbc"
      Hint: MetaKeywords
      Value: AFL Environmental Sustainability and Stewardship EHS health safety
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Environmental Sustainability
    - ID: "628db04b-29a2-483b-a88c-b8fd9a5f2086"
      Hint: HeroLink
      Value: |
        <link id="{F32459CE-4C84-4719-A8C4-BEBE908499D7}" querystring="" target="|Custom" text="LEARN MORE" anchor="" url="/AFL-Global/AMERICAS/Home/Company/Corporate Responsibility/Environmental Sustainability" title="" class="" linktype="internal" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: Environmental Sustainability
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb51f281-fe1c-4680-a90c-89b53fb8fd90"
    - ID: "93dc88f3-05e5-482d-9b9a-c859c8258a73"
      Hint: HeroBackgroundImage
      Value: |
        <image mediaid="" stylelabs-content-id="168676" thumbnailsrc="https://afl.stylelabs.cloud/api/gateway/168676/thumbnail" src="https://afl-delivery.stylelabs.cloud/api/public/content/bb7394c51f0c456f936ec6e57daca5ca?v=c6b306d8" stylelabs-content-type="Image" alt="company-ehs.jpg" height="369" width="954" />
    - ID: "a40ebd3d-2b41-41fb-90f7-753544ce77c5"
      Hint: Hero Title1
      Value: Environmental Sustainability
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pawan.tyagi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240316T041637Z
    - ID: "dd0b26a2-9ca3-4573-b501-3b33a6efbc65"
      Hint: Hero Title2
      Value: Focused on environmental stewardship to achieve our business goals
