---
ID: "0ab2e3c5-fd41-4316-ac1f-6601b4ec6496"
Parent: "4188b4df-19aa-4c04-b3ec-5e9ed25b61c3"
Template: "4188b4df-19aa-4c04-b3ec-5e9ed25b61c3"
Path: /sitecore/templates/Project/AFLGlobal/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240215T104728Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\gunasekaran.s@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\gunasekaran.s@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1814f1d4-f7a8-42a1-b9d6-3e257297cd75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gunasekaran.s@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240215T104728Z
