---
ID: "40cf2536-cfa7-400a-baff-df06d2d2d2c7"
Parent: "e8b08ae7-ed24-4a3e-a1f5-ef438ee42711"
Template: "c14b6289-8ac2-439c-9e5b-40de9f820c3f"
Path: "/sitecore/content/AFL-Global/APAC/Home/Company/Environment Health Safety/Environmental Sustainability"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{D7C0086B-FD36-430A-807E-023D55F307AE}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231004T182847Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d644a937-8564-44c9-b1ed-394994196841"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rafael
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231004T183010Z
