---
ID: "0be16cfa-7fb1-4fe4-ac0a-f15cceecabb6"
Parent: "01de7ed7-d2cd-4a46-8e81-b7896cabd637"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/AFLGlobal/aflglobal/Presentation/Headless Variants/Title/Default
BranchID: "3f7de82f-366f-4708-a1fe-9b0a42862492"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{17537200-43DF-4384-85AD-8C795BB461E6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240328T054915Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "988c224a-c623-4ea7-b012-0ec0e9b70f1e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240328T054915Z
