---
ID: "5d1b6b6a-1912-48dc-a2f8-1f0035fda269"
Parent: "84c2b92d-e946-44ac-824f-64c37c91d1a6"
Template: "178e3cec-ca03-4c76-9ad3-122297e19e13"
Path: /sitecore/content/AFLGlobal/APAC/Home/Products/Test and Inspection/Test Management and Reporting Software/ROGUE OLTSCertification App/Additional Image/app
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220405T050907Z
    - ID: "4f4e6526-41d1-4a67-ba95-3cf65c6a6462"
      Hint: ImgaeUrl
      Value: |
        <image stylelabs-content-id="227516" src="https://afl-delivery.stylelabs.cloud/api/public/content/fc4ef399d9304f1fb4d9370984bb9afc?v=c09f49fb" stylelabs-content-type="Image" alt="1758" thumbnailsrc="https://afl.stylelabs.cloud/api/gateway/227516/thumbnail" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mahesh
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mahesh
    - ID: "80203708-a0db-4f4b-bd18-b5f74b33756d"
      Hint: ImageTitle
      Value: app
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f30b5700-67ef-4f20-aaf7-63aff3017f11"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mahesh
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220405T050907Z
