---
ID: "c4aa8b01-670a-4dad-bd30-3cb6c14abb3c"
Parent: "62fffab9-86bb-41a5-b5cc-1a268672f148"
Template: "62fffab9-86bb-41a5-b5cc-1a268672f148"
Path: /sitecore/templates/Project/AFLGlobal/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240328T054550Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d40fe53b-d9aa-49ac-abd8-14e8fa541602"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asmita.parkar@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240328T054550Z
