---
ID: "34dd0326-fed3-4a32-a7f7-39221aa58f94"
Parent: "9f1bfdd2-dfdd-4bb3-9a53-47a832db07cf"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: "/sitecore/content/AFL-Global/APAC/Settings/Datasource Configurations"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211027T075725Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb8fce43-a2ed-4d2d-a83d-83e97ea46638"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211027T075725Z
