---
ID: "b3bfc308-129b-4ba2-9276-0279bfaf55f7"
Parent: "9f1bfdd2-dfdd-4bb3-9a53-47a832db07cf"
Template: "18d0bd79-7da4-4c2a-a924-b93a2b99d669"
Path: "/sitecore/content/AFL-Global/APAC/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211027T075726Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ae3bdbd-aa67-41b3-85c7-87e2bedaf7db"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211027T075726Z
