---
ID: "d2e1eb5d-e1d2-4fce-a381-13b818c54003"
Parent: "42fdc709-ba96-4169-af29-f0445e1f59a1"
Template: "c14b6289-8ac2-439c-9e5b-40de9f820c3f"
Path: "/sitecore/content/AFL-Global/AMERICAS/Home/Company/Environment Health Safety/Environmental Sustainability"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{F32459CE-4C84-4719-A8C4-BEBE908499D7}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231004T153526Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ae99651d-374c-41da-b847-8cef26c10442"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rafael
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231018T183909Z
