---
ID: "93279959-28ba-4418-a42a-a1819c87ad03"
Parent: "d89ffc80-a903-4629-9376-7be3f3961ec1"
Template: "bf61de11-b78f-48ea-aaa4-1d17f0d83824"
Path: "/sitecore/content/AFL-Global/APAC/Home/Contact/Contacts and Feedback Forms/Product Service Request Form"
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{87CE798E-CDA3-4363-A47F-74DF3E2D88BE}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{DAE7C21D-4D3B-4257-A95C-9104CD8AF409}"
- ID: "db51d4e9-c24d-4670-af0e-62c8aa08e2b6"
  Hint: LocalData
  Value: "{2AF5FE0C-8E43-43FE-A1ED-29D43E3EA954}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{220F8928-C60C-4E32-BCEB-E62138FAE0F7}"
              s:ds="local:/Data/HTML Code 2"
              s:id="{6DDA07A9-18D3-47A0-AB74-DF54956DD5F1}"
              s:par="Reset Caching Options&amp;GridParameters={908E2BC6-C110-4ED7-AF39-7EEACBB31A34}&amp;Styles&amp;CacheClearingBehavior=Clear on publish&amp;RenderingIdentifier"
              s:ph="/main/sxa-high-level-page/container-5" />
          </d>
        </r>
    - ID: "22753447-be25-4035-a3c9-7f875afe8e57"
      Hint: RedirectUrl
      Value: |
        <link linktype="external" url="https://www.aflglobal.com/en/Contact/Contacts-and-Feedback-Forms/Product-Service-Request-Form" anchor="" target="_blank" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220311T204756Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EE9BAFE9-A55E-406B-8BBF-45ADF7FF9068}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Service Request
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rafael
    - ID: "528986cc-6ff9-4383-8bee-514f0e8172cf"
      Hint: MetaDescription
      Value: Use the Product Service Request Form to request service support for Fujikura Splicers.
    - ID: "52b07316-e493-41de-8a4f-d5010dc3eebd"
      Hint: Description
      Value: |
        <h1 style="color: #000000; background-color: #ffffff; margin: 0.67em 0px; line-height: 24px;">Product Service Request Form</h1>
        <h3 style="color: #282828; background-color: #ffffff; margin: 0px;">Complete all required fields on this form for a service request for <a href="~/link.aspx?_id=55E85DE502FD4DF7A029245253934A91&_z=z">Fusion Splicer</a> or <a href="~/link.aspx?_id=67697A36EE374C21A1F009672463F0E6&_z=z">Test and Inspection</a> equipment. We will respond shortly with a service request number and shipping information.</h3>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rafael
    - ID: "5e650555-c7f0-456a-8185-f69388169cbc"
      Hint: MetaKeywords
      Value: Product Service Request Form
    - ID: "60d29626-f584-4bc5-b7c1-8d5c39a77b07"
      Hint: Title
      Value: Product Service Request Form
    - ID: "612fc437-a34e-408c-a80f-a3ce18887805"
      Hint: SuggestionBoxRedirectIcon
      Value: |
        <image mediaid="{5A901871-5681-4DAD-ABC1-FB375934B088}" alt="Suggestion Box" height="" width="" hspace="" vspace="" />
    - ID: "7d988161-3991-465a-a88c-280bc65542a0"
      Hint: OpenGraphTitle
      Value: Product Service Request Form
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5edcc948-4f7b-469d-9fb1-7edc49ef3b28"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Abhishek
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231213T101604Z
